<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationManifest>RevitAPI.addin</ApplicationManifest>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <LangVersion>latest</LangVersion>
	  <UseWPF>true</UseWPF>
	  <StartAction>Program</StartAction>
	  <StartProgram>C:\Program Files\Autodesk\Revit 2026\Revit.exe</StartProgram>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\General_Test32.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

	<ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>..\..\..\..\..\Program Files\Autodesk\Revit 2026\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\..\..\..\..\Program Files\Autodesk\Revit 2026\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\General_Test32.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\icon16.png" />
    <Resource Include="Resources\icon32.png" />
  </ItemGroup>

</Project>
